### ISSUE TITLE
When Activity's property "configChanges"  value has "layoutDirection" get the error

### ISSUE THREAD

**Issue by ammmmmmmmmmmmm** [dodorare/android-manifest-rs#2]
Hi, My activity's property "android:configChanges" contain "layoutDirection". When I parse xml get a error :
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Message("unknown variant `layoutDirection`, expected one of `density`, `fontScale`, `keyboard`, `keyboardHidden`, `layoutDiraction`, `locale`, `mcc`, `mnc`, `navigation`, `orientation`, `screenLayout`, `screenSize`, `smallestScreenSize`, `touchscreen`, `uiMode`")'
```
thank you!

**Comment by olvyko** [comment]
@ammmmmmmmmmmmm Hi, sorry for the delayed response. If I understood correctly after searching, `layoutDirection` isn't variant for `android:configChanges`. But you can customize the `layoutDirection` directly in each layout or in styles.

Example:
in `app/res/values/styles`:
```xml
<style name"YourMainThemeName" parent="Parent Theme Of Your Choice">
    <item name="android:layoutDirection">rtl</item>
    <item name="windowActionBar">false</item>
</style>
```
and in `app/manifests/AndroidManifest.xml`:
```xml
<application
        android:supportsRtl="true"
        android:theme="@style/YourMainThemeName">
</application>
```

Useful links:
https://developer.android.com/reference/android/view/View#attr_android:layoutDirection
https://stackoverflow.com/questions/31904627/android-change-entire-app-layout-directions-programmatically

**Comment by ammmmmmmmmmmmm** [comment]
Thank you for your reply!  I found the link below, `android:configChanges` has a `layoutDirection ` value
`Added in API level 17.`
https://developer.android.com/guide/topics/manifest/activity-element#config

**Comment by enfipy** [comment]
@ammmmmmmmmmmmm Sorry and thank you for the issue, this was our bug. It is fixed and closed. You can use commit message or wait till we check all the code for similar problems and publish a new release. It will take no more than three days.
