### ISSUE TITLE
from_str() returns error while parsing xml containing empty android:labels

### ISSUE THREAD

**Issue by black-binary** [dodorare/android-manifest-rs#4]
I got a strange APK file whose manifest xml file contains activity with empty `android:label` and from_str() failed to parse it.

reprex:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:compileSdkVersion="29" android:compileSdkVersionCodename="10" package="com.test" platformBuildVersionCode="29" platformBuildVersionName="10">
    <application android:name="com.test">
        <activity android:exported="true" android:label="" android:name="com.some.activitiy" />
    </application>
</manifest>
```

But it works if I simply delete the attribute, or fill in anything else:

```
 <activity android:exported="true" android:name="com.some.activitiy" />
```
or
```
<activity android:exported="true" android:label="blablabla" android:name="com.some.activitiy" />
```

Is this an expected behavior or a bug?

**Comment by Adoka3710** [comment]
`android:label` is an optional attribute. It has a custom type called `"StringResourceOrString"` which includes if the string is empty or not. We've added a check to if its empty or not, we think it might be correct. Is this important for you?
