### ISSUE TITLE
some android node attribute

### ISSUE THREAD

**Issue by xiangyuan** [dodorare/android-manifest-rs#9]
example one: `<application android:name="xxx" android:allowBackup="false" tools:replace="android:allowBackup" android:networkSecurityConfig="@xml/network_security_config" android:extractNativeLibs="true" android:isGame="true">`

something like the tools:replace  can not parsed  android:extractNativeLibs maybe

example two: 
`<intent-filter android:autoVerify="true">`
the filter andorid:autoVerify  can not parsed too

**Comment by enfipy** [comment]
Thanks for the issue. Can you provide the information on the version you used?

I think [android:autoVerify](https://github.com/dodorare/android-manifest-rs/blob/main/src/intent_filter.rs#L156) and [android:extractNativeLibs](https://github.com/dodorare/android-manifest-rs/blob/main/src/application.rs#L266) should be valid and parsed. Please provide some more context on how to reproduce the error.

Regarding [tools:replace](https://developer.android.com/build/manage-manifests#merge_rule_markers) and other [tools attributes](https://developer.android.com/studio/write/tool-attributes) - this feature is indeed isn't implemented as of now. So I recommend to open a new Feature Request issue for this functionality.

**Comment by xiangyuan** [comment]
> Thanks for the issue. Can you provide the information on the version you used?
> 
> I think [android:autoVerify](https://github.com/dodorare/android-manifest-rs/blob/main/src/intent_filter.rs#L156) and [android:extractNativeLibs](https://github.com/dodorare/android-manifest-rs/blob/main/src/application.rs#L266) should be valid and parsed. Please provide some more context on how to reproduce the error.
> 
> Regarding [tools:replace](https://developer.android.com/build/manage-manifests#merge_rule_markers) and other [tools attributes](https://developer.android.com/studio/write/tool-attributes) - this feature is indeed isn't implemented as of now. So I recommend to open a new Feature Request issue for this functionality.

`android-manifest = "0.1.4"` now I am using, i will test the latest version thanks
